#!/usr/bin/env bash

set -aeuo pipefail
source ./.env

echo "rm all marked files"
rm  -rf ./.docker/*.flag
rm  -rf ./.docker/*.txt

echo "stop modules and remove images"
./docker-compose down --rmi local --volumes

echo 'docker images ls -q '
echo "***************************"
docker images ls -q
echo "***************************"
echo 'docker container ls -q '
echo "***************************"
docker container ls -q
echo "***************************"


{  #try
    echo 'docker volume ls -q | grep '${COMPOSE_PROJECT_NAME}
    echo "***************************"
    docker volume ls -q | grep ${COMPOSE_PROJECT_NAME}
    echo "***************************"
} || {  #catch
    # do nothing here.
    echo ''
}

# remove all images
{
    echo 'First Step: remove all image'
    docker rmi -f $(docker image ls -q) 2> /dev/null
} || {
    # save log for exception
    echo "Try to remove all images were finished."
}

{  #try
    echo 'Second Step: remove all containers'
    docker container rm -f $(docker container ls -q) 2> /dev/null
} || {  #catch
    echo "all containers were removed."
}

# don't remove all volume anymore
if [ ${ONLY_DELETE_CURRENT_PROJECT_VOLUME} == true ]; then
    {  #try
        echo 'Third Step : remove all current project volumes'
        docker volume rm -f $(docker volume ls -q | grep ${COMPOSE_PROJECT_NAME}) 2> /dev/null
    } || {  #catch
        # save log for exception
        echo "all current project volumes were removed."
    }
else
    {  #try
        echo 'Third Step : remove all volumes'
        docker volume rm -f $(docker volume ls -q ) 2> /dev/null
    } || {  #catch
        # save log for exception
        echo "all volumes were removed."
    }
fi

{ # try
    docker stop $(docker ps -a | grep ${COMPOSE_PROJECT_NAME} | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "all current project exited containers were stopped."
}

{ # try
    docker rm $(docker ps -a | grep ${COMPOSE_PROJECT_NAME} | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "all current project exited containers were removed."
}
echo '&&&&&'
echo "Checking Start"
echo '&&&&&'
echo "docker image ls -q"
echo "***************************"
docker image ls -q
echo "***************************"
echo "docker container ls -q"
echo "***************************"
docker container ls -q
echo "***************************"
echo "docker volume ls -q"
echo "***************************"
docker volume ls -q
echo "***************************"
echo '&&&&&'
echo "Checking End"
echo '&&&&&'
