#!/usr/bin/env bash
set -aeuo pipefail

echo "try to add +x rights for : chmod +x ./stop ./start ./restart ./remove ./go ./upgrade ./docker-compose";
chmod +x ./stop ./start ./restart ./remove ./go ./upgrade ./docker-compose
echo 'try to chmod 777 to  ./.docker/mysql/log ./.docker/nginx'
chmod -R 777 ./.docker/mysql/log ./.docker/nginx ./.docker/elasticsearch/data

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

pwd
source ./.env

#try to create docker-compose.dev.yml if not
if [ ! -f docker-compose.dev.yml ]; then
  if [ ${NUXT_JS_PROJ} == true ]; then
    cp docker-compose.dev.yml.full.sample docker-compose.dev.yml
  else
    cp docker-compose.dev.yml.sample docker-compose.dev.yml
  fi
fi

echo 'docker container ls'
echo "***************************"
docker container ls
echo "***************************"

echo 'docker volume ls'
echo "***************************"
docker volume ls
echo "***************************"

echo "starting containers"
echo "***************************"
./docker-compose up $@
