#!/usr/bin/env bash
set -aeuo pipefail

echo "try to add +x rights for : chmod +x ./stop ./start ./restart ./remove ./go ./upgrade ./docker-compose";
chmod +x ./stop ./start ./restart ./remove ./go ./upgrade ./docker-compose
echo 'try to chmod 777 to  sudo ./.docker/mysql/log ./.docker/elasticsearch/data'
echo 'If you do not have sudo right, please remove these lines(6-7) in ./start file'
chmod -R 777 ./.docker/mysql/log ./.docker/elasticsearch/data

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

pwd
source ./.env

#try to create docker-compose.dev.yml if not
if [ ! -f docker-compose.dev.yml ]; then
  if [ ${RUN_TYPE} == 'FULL' ]; then
    cp docker-compose.dev.yml.full.sample docker-compose.dev.yml
  elif [ ${RUN_TYPE} == 'SIMPLE' ]; then
    cp docker-compose.dev.yml.simple.sample docker-compose.dev.yml
    if [ -f .docker/nginx/etc/conf.d/php73_fastcgi_backend.conf ]; then
      mv .docker/nginx/etc/conf.d/php73_fastcgi_backend.conf .docker/nginx/etc/conf.d/php73_fastcgi_backend.conf.sample
    fi
    if [ -f .docker/nginx/etc/conf.d/php73_demo.conf ]; then
      mv .docker/nginx/etc/conf.d/php73_demo.conf .docker/nginx/etc/conf.d/php73_demo.conf.sample
    fi
  elif [ ${RUN_TYPE} == 'APPLESILICON' ]; then
      cp docker-compose.dev.yml.applesilicon.sample docker-compose.dev.yml
  else
    cp docker-compose.dev.yml.sample docker-compose.dev.yml
  fi
fi

echo 'docker container ls'
echo "***************************"
docker container ls
echo "***************************"

echo 'docker volume ls'
echo "***************************"
docker volume ls
echo "***************************"

echo "starting containers"
echo "***************************"
./docker-compose up $@
