#!/usr/bin/env bash
set -aeuo pipefail

source ./.env

echo "stop containers"
./docker-compose down --rmi local
echo 'docker image ls -q'
echo "***************************"
docker images ls -q
echo "***************************"
echo 'docker container ls -q'
echo "***************************"
docker container ls -q
echo "***************************"
echo 'docker volume ls -q'
echo "***************************"
docker volume ls -q
echo "***************************"


{ # try
    echo 'Second Step: remove all containers from ' ${COMPOSE_PROJECT_NAME}
    docker container rm -f $(docker container ls -q | grep ${COMPOSE_PROJECT_NAME}) 2> /dev/null
} || { # catch
    echo "Try to remove containers skip."
}

{ # try
    docker stop $(docker ps -a | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "Try to stop all container skip."
}

{ # try
    docker rm $(docker ps -a | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "Try to remove all container skip."
}

echo "docker image ls -q"
docker image ls
echo "***************************"
echo "docker container ls -q"
docker container ls -q
echo "***************************"
echo "docker volume ls -q"
docker volume ls -q
