#!/usr/bin/env bash
set -aeuo pipefail

source ./.env

echo "stop containers"
./docker-compose down --rmi local

echo 'docker image ls -q'
echo "***************************"
docker images ls -q
echo "***************************"
echo 'docker container ls -q'
echo "***************************"
docker container ls -q
echo "***************************"
echo 'docker volume ls -q'
echo "***************************"
docker volume ls -q
echo "***************************"

# it is not easy to fetch all images, so kept it in default
{
    echo 'First Step : remove all images'
    docker rmi -f $(docker images -q) 2> /dev/null
} || {
    # save log for exception
    echo "Try to remove images failed."
}

{ # try
    echo 'Second Step : remove all containers'
    docker container rm -f $(docker container ls -q) 2> /dev/null
} || { # catch
    echo "Try to remove containers failed."
}

{ # try
    docker stop $(docker ps -a | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "Try to stop all container failed."
}

{ # try
    docker rm $(docker ps -a | grep "Exited" | awk '{print $1 }')  2> /dev/null
} || { # catch
    # save log for exception
    echo "Try to remove all container failed."
}

echo "docker image ls -q"
docker image ls
echo "***************************"
echo "docker container ls -q"
docker container ls -q
echo "***************************"

echo "Try to git pull"
git pull
echo "***************************"

echo "Upgrade successfully, please run <./start> to start again."
echo "***************************"

